trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
- group: BuildPipelineVariables
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'x64'
- name: buildConfigurationDebug
  value: 'Debug'
- name: buildConfigurationRelease
  value: 'Release'
- name: buildConfigurationSideload
  value: 'Sideload'
- name: appxPackageDir
  value: '$(build.artifactStagingDirectory)\AppxPackages\\'

jobs:

# Debug
- job: BuildDebugx64
  displayName: Build Debug x64
  timeoutInMinutes: 120

  steps:
  - task: PowerShell@2
    displayName: 'Canonicalize package manifest'
    inputs:
      targetType: 'inline'
      script: |
        [xml]$xmlDoc = Get-Content $(Build.SourcesDirectory)\src\RegistryValley.App\Package.appxmanifest
        $xmlDoc.Package.Identity.Name="RegistryValleyDebug"
        $xmlDoc.Package.Identity.Publisher="CN=RegistryValley"
        $xmlDoc.Package.Properties.DisplayName="RegistryValley"
        $xmlDoc.Package.Applications.Application.VisualElements.DisplayName="RegistryValley"
        $xmlDoc.Save('$(Build.SourcesDirectory)\src\RegistryValley.App\Package.appxmanifest')
      failOnStderr: true

  - task: DownloadSecureFile@1
    name: caCertificate
    displayName: 'Download CA certificate'
    inputs:
      secureFile: '$(signingCert.secureFilePath)'

  - task: UseDotNet@2
    displayName: 'Install .NET'
    inputs:
      packageType: sdk
      version: 7.0.x
      includePreviewVersions: true

  - task: MSBuild@1
    displayName: 'Restore projects'
    inputs:
      platform: 'x64'
      solution: '$(solution)'
      configuration: '$(buildConfigurationDebug)'
      msbuildArguments: '
      /t:restore
      /p:Configuration="$(buildConfigurationDebug)"
      /p:Platform="$(buildPlatform)"
      /p:PublishReadyToRun=true'
      maximumCpuCount: true

  - task: MSBuild@1
    displayName: 'Build RegistryValley'
    inputs:
      platform: 'x64'
      solution: '$(solution)'
      configuration: '$(buildConfigurationDebug)'
      msbuildArgs: '
      /t:build;_GenerateAppxPackage
      /p:Configuration=Debug
      /p:Platform="$(buildPlatform)"
      /p:AppxBundle=Always
      /p:AppxBundlePlatforms="$(buildPlatform)"
      /p:AppxPackageDir="$(appxPackageDir)"
      /p:AppxPackageSigningEnabled=true
      /p:UapAppxPackageBuildMode=SideloadOnly
      /p:PackageCertificateKeyFile="$(caCertificate.secureFilePath)"
      /p:PackageCertificatePassword="$(signingCert.password)"
      /p:PackageCertificateThumbprint=""'
      maximumCpuCount: true

  - task: CopyFiles@2
    displayName: 'Copy artifacts'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**\bin\$(buildConfigurationDebug)\**'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      artifactName: 'Debug'

# Sideload
- job: BuildSideloadx64
  displayName: Build Sideload x64
  timeoutInMinutes: 120

  steps:
  - task: PowerShell@2
    displayName: 'Edit Package.appxmanifest'
    inputs:
      targetType: 'inline'
      script: |
        [xml]$xmlDoc = Get-Content $(Build.SourcesDirectory)\src\RegistryValley.App\Package.appxmanifest
        $xmlDoc.Package.Identity.Name="RegistryValleySideload"
        $xmlDoc.Package.Identity.Publisher="CN=RegistryValley"
        $xmlDoc.Package.Properties.DisplayName="RegistryValley"
        $xmlDoc.Package.Applications.Application.VisualElements.DisplayName="RegistryValley"
        $xmlDoc.Save('$(Build.SourcesDirectory)\src\RegistryValley.App\Package.appxmanifest')
      failOnStderr: true

  - task: DownloadSecureFile@1
    name: caCertificate
    displayName: 'Download CA certificate'
    inputs:
      secureFile: '$(signingCert.secureFilePath)'

  - task: UseDotNet@2
    displayName: 'Install .NET'
    inputs:
      packageType: sdk
      version: 7.0.x
      includePreviewVersions: true

  - task: MSBuild@1
    displayName: 'Restore projects'
    inputs:
      platform: 'x64'
      solution: '$(solution)'
      configuration: '$(buildConfigurationSideload)'
      msbuildArguments: '
      /t:restore
      /p:Configuration="$(buildConfigurationSideload)"
      /p:Platform="$(buildPlatform)"
      /p:PublishReadyToRun=true'
      maximumCpuCount: true

  - task: MSBuild@1
    displayName: 'Build RegistryValley'
    inputs:
      configuration: '$(buildConfigurationSideload)'
      platform: 'x64'
      solution: '$(solution)'
      msbuildArgs: '
      /t:build;_GenerateAppxPackage
      /p:AppxLogTelemetryFromSideloadingScript=False
      /p:GenerateAppInstallerFile=True
      /p:AppxBundlePlatforms="$(buildPlatform)"
      /p:AppxPackageDir="$(appxPackageDir)"
      /p:AppxBundle=Always
      /p:UapAppxPackageBuildMode=Sideload
      /p:AppxPackageSigningEnabled=true
      /p:PackageCertificateKeyFile="$(caCertificate.secureFilePath)"
      /p:PackageCertificatePassword="$(signingCert.password)"
      /p:PackageCertificateThumbprint=""'
      maximumCpuCount: true

  - task: CopyFiles@2
    displayName: 'Copy artifacts'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**\bin\$(buildConfigurationSideload)\**'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      artifactName: 'Sideload'

# StoreUpload
- job: BuildStoreUploadx64
  displayName: Build StoreUpload x64
  timeoutInMinutes: 120

  steps:
  - task: PowerShell@2
    displayName: 'Edit Package.appxmanifest'
    inputs:
      targetType: 'inline'
      script: |
        [xml]$xmlDoc = Get-Content $(Build.SourcesDirectory)\src\RegistryValley.App\Package.appxmanifest
        $xmlDoc.Package.Identity.Name="49462fluenthub-uwp.RegistryValley"
        $xmlDoc.Package.Identity.Publisher="CN=4E3C0825-4D00-4ECC-89F8-528E9200B125"
        $xmlDoc.Package.Properties.DisplayName="RegistryValley"
        $xmlDoc.Package.Applications.Application.VisualElements.DisplayName="RegistryValley"
        $xmlDoc.Save('$(Build.SourcesDirectory)\src\RegistryValley.App\Package.appxmanifest')
      failOnStderr: true

  - task: DownloadSecureFile@1
    name: caCertificate
    displayName: 'Download CA certificate'
    inputs:
      secureFile: '$(signingCert.secureFilePath)'

  - task: UseDotNet@2
    displayName: 'Install .NET'
    inputs:
      packageType: sdk
      version: 7.0.x
      includePreviewVersions: true

  - task: MSBuild@1
    displayName: 'Restore projects'
    inputs:
      platform: 'x64'
      solution: '$(solution)'
      configuration: '$(buildConfigurationRelease)'
      msbuildArguments: '
      /t:restore
      /p:Configuration="$(buildConfigurationRelease)"
      /p:Platform="$(buildPlatform)"
      /p:PublishReadyToRun=true'
      maximumCpuCount: true

  - task: MSBuild@1
    displayName: 'Build RegistryValley'
    inputs:
      configuration: '$(buildConfigurationRelease)'
      platform: 'x64'
      solution: '$(solution)'
      msbuildArguments: '
      /t:build;_GenerateAppxPackage
      /p:AppxBundlePlatforms="$(buildPlatform)"
      /p:AppxBundle=Always
      /p:AppxPackageDir="$(appxPackageDir)"
      /p:UapAppxPackageBuildMode=StoreUpload'
      maximumCpuCount: true

  - task: CopyFiles@2
    displayName: 'Copy artifacts'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**\bin\$(buildConfigurationRelease)\**'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      artifactName: 'StoreUpload'
